PUT http://localhost:3001/api/blogs/6103f19b9c434f21cc648c33
Content-Type: application/json

{
    "title":"new blog",
    "author":"author",
    "url":"http://localhost:3001/api/blogs",
    "likes":0,
    "userId": "6107a9959a5d3652f8137cf7"
}